# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://gongenbo.github.io
date_format: "ordinal"
title: 巩恩伯
subtitle: "Keep the faith!"
description: "巩恩伯的博客"
keywords: 巩恩伯
favicon: /favicon.ico
timezone: Asia/BeiJing
encoding: "utf-8"
source_code: https://github.com/gongenbo/gongenbo.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 巩恩伯
location: BeiJing, China
email: username@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 博客

  -
    href: /categories/
    label: 目录

  -
    href: /MySkillTree/
    label: 技能树

  -
    href: /about/
    label: 关于我

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: gongenbo
facebook_username: gongenbo
weibo_username: enbo
zhihu_username: gongenbo
twitter_username: enbogong

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan，livere(来必力)
comments_provider: disqus
# !!!重要!!! 请修改下面用户名为你自己申请的
disqus_username: gongenbo

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: GTM-NJVCNRZ

# ---------------- #
#      Datas       #
# ---------------- #
skill_language_keywords: [Java, Python, C++]
skill_data_science_keywords: [Hadoop, Spark, MapReduce, Hive]
skill_machine_learning_keywords: [推荐, NLP, 计算机视觉]
# 组件配置
components:
  # 不蒜子访问统计
  busuanzi:
    enabled: true
    start_date: 2020-08-02
# 文章字数统计
word_count:
  enabled: true